# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  deploy:
    docker: 
      - image: 'ishaker/aws-ecscli'
    steps:
      - checkout
      - run:
          name: Deploy ecs
          command: |
            ./deploy.sh
workflows:
  version: 2.1
  front:
    jobs:
      - deploy
 

